#!/usr/bin/env php
<?php

/**
 * PHP CLI Excutable file. Outputs the required WordPress keys and salts in
 * either the traditional WordPress define format or the Composer driven
 * DotEnv format.
 *
 * When loaded via composer this file can be executed in CLI as follows:
 * vendor/bin/wpsalts
 *
 * @author Rob Waller <rdwaller1984@googlemail.com>
 */


/**
 * Load the correct autoloader dependent on how this file is being executed.
 */
$paths = [
    __DIR__ . '/vendor/autoload.php',
    __DIR__ . '/../../autoload.php'
];

foreach ($paths as $path) {
    if (file_exists($path)) {
        require_once $path;
        break;
    }
}

/**
 * Load the WordPress salts class
 */
$salts = new \Sanket\Envgenerator\Salts;

/**
 * Return the WordPress salts in a DotEnv format for use in .env files.
 */
echo $salts->copyfolder(__DIR__, 'sanket');
die();